version: '3.7'

services:
  fastapi:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    # image: fastapiapp:v2
    ports:
      - '8000:80'
    volumes:
      - ./app/songs.json:/code/app/songs.json