version: '3.7'

services:

  sample-prod:
    container_name: sample-prod
    build:
      context: ./React/
      dockerfile: Dockerfile.prod
    ports:
      - '3000:80'
  fastapi:
    container_name: backend
    build:
      context: ./FastAPI/
      dockerfile: Dockerfile
    ports:
      - '8000:80'
    volumes:
      - ./FastAPI/app/songs.json:/code/app/songs.json
